// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------

using AterraCore.Common.FlexiPlug;

namespace AterraCore.Common.Nexities;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------

public struct AssetRegistration {
    // Generated by PluginLoader
    public PluginId PluginId { get; init; }
    
    // Actual type of class
    public Type Type { get; init; }
    
    // Data from AbstractAssetAttribute
    public PartialAssetId PartialAssetId { get; init; }
    public AssetInstanceType InstanceType { get; init; }
    public CoreTags CoreTags { get; init; }

    // Data from AbstractAssetTagAttribute
    public IEnumerable<string> StringTags { get; init; }
    
}