<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AterraEngine.Common\AterraEngine.Common.csproj"/>
        <ProjectReference Include="..\AterraEngine.Contracts\AterraEngine.Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AterraEngine.DependencyInjection" Version="4.13.0" />
      <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.4" />
    </ItemGroup>

</Project>
