<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AterraEngine.DependencyInjection" Version="4.13.0" />
      <PackageReference Include="AterraEngine.DependencyInjection.Bridges.Microsoft" Version="4.13.0" />
      <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" Version="0.59.0" />
      <PackageReference Include="CodeOfChaos.Extensions.Serilog" Version="0.59.0" />
      <PackageReference Include="CodeOfChaos.Types.TypedValueStore" Version="0.25.1" />
      <PackageReference Include="Serilog" Version="4.2.0" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
      <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\AterraEngine.Contracts\AterraEngine.Contracts.csproj" />
      <ProjectReference Include="..\..\src\AterraEngine.Frameworks.Omnia.PreProcessor\AterraEngine.Frameworks.Omnia.PreProcessor.csproj" />
      <ProjectReference Include="..\..\src\AterraEngine.Frameworks.Omnia\AterraEngine.Frameworks.Omnia.csproj" />
      <ProjectReference Include="..\..\src\AterraEngine\AterraEngine.csproj" />
    </ItemGroup>

</Project>
