<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <RootNamespace>AterraEngine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AterraEngine.Common\AterraEngine.Common.csproj" />
    </ItemGroup>

</Project>
