<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AterraEngine.Common\AterraEngine.Common.csproj"/>
        <ProjectReference Include="..\..\src\AterraEngine.Contracts\AterraEngine.Contracts.csproj"/>
        <ProjectReference Include="..\..\src\AterraEngine.Frameworks.Nexities\AterraEngine.Frameworks.Nexities.csproj"/>
        <ProjectReference Include="..\..\src\AterraEngine\AterraEngine.csproj"/>
    </ItemGroup>

</Project>
