<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.Extensions.ObjectPool" />
      <PackageReference Include="Raylib-cs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AterraEngine.Contracts\AterraEngine.Contracts.csproj" />
      <ProjectReference Include="..\AterraEngine.Frameworks.Nexities.Shared\AterraEngine.Frameworks.Nexities.Shared.csproj" />
    </ItemGroup>

</Project>
