<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.DependencyInjection" Version="4.13.0" />
        <PackageReference Include="AterraEngine.DependencyInjection.Contracts" Version="4.13.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AterraEngine.Frameworks.Continuum\AterraEngine.Frameworks.Continuum.csproj"/>
    </ItemGroup>

</Project>
