name: User Story
description: Template for creating user stories
title: "[UserStory]: "
labels: ["user-story"]
projects: ["AterraEngine/1"]
assignees:
  - AndreasSasDev

body:
  - type: markdown
    attributes:
      value: |
        ### User Story

        Please fill out the details of the user story below.

  - type: input
    id: role
    attributes:
      label: Role
      description: Who is this feature for? (e.g., As a GameDev, As an EngineDev)
      placeholder: ex. As a GameDev
    validations:
      required: true

  - type: input
    id: feature
    attributes:
      label: Feature
      description: What is the feature or functionality needed? (e.g., I want to have a framework for ...)
      placeholder: ex. I want to be able to log in
    validations:
      required: true

  - type: input
    id: benefit
    attributes:
      label: Benefit
      description: Why is this feature important? What value does it add? (e.g., So that I can access my account)
      placeholder: ex. So that I can access my account
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any other context, links, or details about the feature. (Optional)
      placeholder: ex. Screenshots, diagrams, or other references
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define the requirements that this story should meet when it is delivered. (Optional but recommended)
      placeholder: ex. Given that I am on the login page, When I enter my credentials, Then I should be redirected to the dashboard
    validations:
      required: false

