<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <RootNamespace>AterraEngine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AterraEngine.Unions" Version="3.11.0"/>
        <PackageReference Include="AterraEngine.Unions.Generators" Version="3.11.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="CodeOfChaos.Extensions" Version="0.40.1" />
    </ItemGroup>

</Project>
