<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <RootNamespace>AterraEngine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AterraEngine.Unions" Version="3.2.1" />
      <PackageReference Include="AterraEngine.Unions.Generators" Version="3.2.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    </ItemGroup>

</Project>
