// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
namespace AterraCore.Common.Types.Nexities;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
public struct AssetRegistration {
    // Generated by PluginLoader
    public AssetId AssetId { get; init; }

    // Actual type of class
    public Type Type { get; init; }
    public Type[] InterfaceTypes { get; init; }

    // Data from AbstractAssetAttribute
    public ServiceLifetimeType ServiceLifetime { get; init; }
    public CoreTags CoreTags { get; init; }

    // Data from AbstractAssetTagAttribute
    public IEnumerable<string> StringTags { get; init; }
}
