// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------

using AterraCore.Common.Types.FlexiPlug;

namespace AterraCore.Common.Types.Nexities;

// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------

public struct AssetRegistration {
    // Generated by PluginLoader
    public PluginId PluginId { get; init; }

    // Actual type of class
    public Type Type { get; init; }
    public Type? InterfaceType { get; init; }

    // Data from AbstractAssetAttribute
    public PartialAssetId PartialAssetId { get; init; }
    public ServiceLifetimeType ServiceLifetime { get; init; }
    public CoreTags CoreTags { get; init; }

    // Data from AbstractAssetTagAttribute
    public IEnumerable<string> StringTags { get; init; }

}
