// ---------------------------------------------------------------------------------------------------------------------
// Imports
// ---------------------------------------------------------------------------------------------------------------------
using AterraEngine.DependencyInjection;
using AterraEngine.Frameworks.Nexities;
using AterraEngine.Frameworks.Omnia;

namespace Workfloor.AterraEngine.Frameworks.Nexities.Generators;
// ---------------------------------------------------------------------------------------------------------------------
// Code
// ---------------------------------------------------------------------------------------------------------------------
[OmniaId("example:entity")]
public partial class Entity : NexitiesEntity, IEntity {
    public partial ExampleComponent ExampleComponent { get; }
    [KeyedInstance("458ebce3-a1b2-4966-8ac2-656c4687881d")] public partial ISomeComponent SomeComponent { get; }
}

public interface ISomeComponent : INexitiesComponent {}

public interface IEntity : INexitiesEntity {}

// Below this point should be auto generated code
// We shouldn't touch any of thi, but it should overrideable? Don't know about that yet
// Technically if I enabled lang=preview I could use the "field" of an auto property, but given it is still in preview.
// ---------------------------------------------------------------------------------------------------------------------

public static class EntityRegistration {
    // Entity should be registered
    public static IServiceCollection AddEntities(IServiceCollection services) {
        services.AddTransientFromFactory<IEntity>(provider => {
            var omniaLibrary = provider.GetRequiredService<IOmniaLibrary>();
            if (!omniaLibrary.TryGetFromPool<IEntity>(out IEntity? newEntity, createFactory: static omniaLib => Entity.CreateNewInstance(omniaLib))) {
                return Entity.CreateNewInstance(omniaLibrary);
            }

            return newEntity;
        });

        return services;
    }
}

file static class Entity_AutoGenerated {
    public static readonly Guid Entity_SomeComponent_KeyedInstance_Id = Guid.Parse("458ebce3-a1b2-4966-8ac2-656c4687881d");
}

public partial class Entity(IScopedProvider provider) {

    private ExampleComponent? _exampleComponent;

    private ISomeComponent? _someComponent;

    public partial ExampleComponent ExampleComponent {
        get {
            if (_exampleComponent is not null) return _exampleComponent;
            if (TryGetComponent(out ExampleComponent? cached)) return _exampleComponent = cached;
            throw new Exception("Could not find ExampleComponent");
        }
    }
    public partial ISomeComponent SomeComponent {
        get {
            if (_someComponent is not null) return _someComponent;
            if (TryGetComponent(out ISomeComponent? cached)) return _someComponent = cached;
            throw new Exception("Could not find ExampleComponent");
        }
    }

    public override void Initialize(OmniaId assetId) {
        base.Initialize(assetId);

        // TODO inject this or go through "EngineServices"
        var library = provider.GetRequiredService<IOmniaLibrary>();

        // Per component we try and fetch it and then try and register it to the omnia library and the internal lookup for the entity 
        if (library.CreateAsset<ExampleComponent>() is not { IsT: true, AsT: {} exampleComponent }) throw new Exception("Could not create ExampleComponent");
        if (!TryRegisterComponent(exampleComponent)) throw new Exception("Could not register ExampleComponent");

        if (library.FindOrCreateAsset<ISomeComponent>(Entity_AutoGenerated.Entity_SomeComponent_KeyedInstance_Id)) is not {
            true,
            {}
            someComponent
        }) throw new Exception("Could not create ExampleComponent");
        if (!TryRegisterComponent(someComponent)) throw new Exception("Could not register ExampleComponent");
    }

    // T
    public static Entity CreateNewInstance(IOmniaLibrary omniaLibrary) {
        var entity = new Entity();

        if (!entity.TryRegisterComponent<ExampleComponent>(omniaLibrary.GetByType<ExampleComponent>())) {
            throw new Exception("Could not register ExampleComponent");
        }

        if (!entity.TryRegisterComponent(omniaLibrary.GetByQuery<ISomeComponent>(instanceId: Entity_AutoGenerated.Entity_SomeComponent_KeyedInstance_Id))) {
            throw new Exception("Could not register ExampleComponent");
        }

        return entity;
    }
}
