<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\AterraEngine.Frameworks.Nexities.Generators\AterraEngine.Frameworks.Nexities.Generators.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Testing.TUnit" Version="0.7.2" />
      <PackageReference Include="TUnit" Version="0.14.6" />
    </ItemGroup>

</Project>
