name: "Run TODO to Issue"
on:
  push:
    branches:
      - core
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          PROJECT: "organization/AterraEngine/Aterra Engine"
          PROJECTS_SECRET: "${{ secrets.PROJECTS_SECRET }}"
          ISSUE_TEMPLATE: |
            ### 📝 Todo : ** {{ title }} **
            **Description:**  
            {{ body }}

            **Code Snippet:**
            {{ snippet }}

            **File:**  
            {{ url }}

          IDENTIFIERS: '[{"name": "TODO", "labels": ["todo"]}]'
          CLOSE_ISSUES: "true"
